services:

  postgres:
    image: postgres:18
    container_name: sudoku-postgres

    environment:
      POSTGRES_DB: sudoku
      POSTGRES_USER: sudoku
      POSTGRES_PASSWORD: sudoku_dev

    ports:
      - "5432:5432"

    volumes:
      - sudoku-postgres-data:/var/lib/postgresql

volumes:
  sudoku-postgres-data:
